name: Generar APK zetanime
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargando Repositorio
        uses: actions/checkout@v3

      - name: Configurando Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalando Herramientas de Capacitor
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android @capacitor/assets

      - name: Inicializando Proyecto Android
        run: |
          # Esto crea la base de la app nativa
          npx cap add android

      - name: Procesando Iconos y Splash JPG
        run: |
          # Usamos tus archivos JPG para que la app tenga tu marca
          npx capacitor-assets generate --android --icon-only assets/icon-only.jpg --splash assets/splash.jpg

      - name: Aplicando Configuración de Rotación
        run: |
          # Este paso asegura que NO se reinicie al girar el celular
          sed -i 's/android:configChanges="orientation|keyboardHidden|screenSize"/android:configChanges="orientation|keyboardHidden|screenSize|smallestScreenSize|screenLayout|uiMode"/g' android/app/src/main/AndroidManifest.xml

      - name: Fabricando APK Finall
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Entregar APK de zetanime
        uses: actions/upload-artifact@v3
        with:
          name: zetanime-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
